---
# tasks file for MariaDB
- name: "instalação do MariaDB"
  apt:
    name:
    - mariadb-server
    - python3-mysqldb
    state: present
  when: ansible_facts["os_family"] == "Debian"
  notify:
    - "Start do MariaDB"
    - "Definindo senha do usuario root"
    - "Criando usuário no banco de dados do GLPI"
    - "Removendo usuários anônimos do MariaDB"
    - "Criando banco de dados do GLPI"