---
# tasks file for Basic
## Atividades relacionadas ao repositorio
- name: "Substitui Arquivo sources.list"
  template:
    src: templates/sources.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    backup: no
  when: ansible_facts["os_family"] == "Debian"

- name: "Instala pacotes essenciais"
  apt:
    name: 
      - python3
    state: present
  when: ansible_facts["os_family"] == "Debian"

## Definir Hostname
- name: "Definir Hostname do computador"
  hostname:
    name: "{{ hostname }}"
  notify: 
    - addInHostsFiles
    - RestartServer
  when: ansible_facts["hostname"] != "{{ hostname }}"

## Atividades relacionadas ao Firewall
- name: "Instala UFW"
  apt:
    name:
      - ufw
    state: present
  notify:
    - "Habilitar acesso SSH"
    - "Habilitar acesso HTTP"
    - "Habilitar acesso HTTPS"
    - "Habilitar acesso MariaDB localhost"
    - "Regra input default - DROP"
    - "Regra outgoing default - ACCEPT"
    - "Habilita o UFW"
  when: ansible_facts["os_family"] == "Debian"