---
# handlers file for Basic
- name: addInHostsFiles
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ hostname }}"

- name: RestartServer
  reboot:

- name: "Atualização do repositorio do Debian"
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  when: ansible_facts['distribution'] == "Debian"

- name: "Habilitar acesso SSH"
  ufw:
    rule: allow
    port: '22'
    proto: tcp
    direction: in
    comment: "INPUT - SSH - ALLOW"

- name: "Habilitar acesso HTTP"
  ufw:
    rule: allow
    port: '80'
    proto: tcp
    direction: in
    comment: "INPUT - HTTP - ALLOW"

- name: "Habilitar acesso HTTPS"
  ufw:
    rule: allow
    port: '443'
    proto: tcp
    direction: in
    comment: "INPUT - HTTPS - ALLOW"

- name: "Habilitar acesso MariaDB localhost"
  ufw:
    rule: allow
    port: '3306'
    proto: tcp
    direction: in
    interface: lo
    comment: "INPUT - MARIADB LOCALHOST - ALLOW"

- name: "Regra input default - DROP"
  ufw:
    state: enabled
    direction: incoming
    policy: deny
    comment: "INPUT - DEFAULT - DENY"

- name: "Regra outgoing default - ACCEPT"
  ufw:
    state: enabled
    direction: outgoing
    policy: allow
    comment: "OUTPUT - DEFAULT - ALLOW"

- name: "Habilita o UFW"
  ufw:
    state: enabled