name: Terraform e Ansible na AWS

on:
  push:
    branches:
      - main # Execute este workflow quando houver push na branch principal
  pull_request:
    branches:
      - main # Execute este workflow quando houver pull request para a branch principal

jobs:
  plan_apply:
    name: Terraform Plan e Apply & Ansible Provisioning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: comando
        run: echo 'Teste Paulo Xavier'
