name: pipeline-terraform-aws

on:
  push:
    branches:
      - main
  paths-ignore:
    - 'README.md'
    - 'certs/**'
  pull_request:
    branches:
      - main

jobs:
    name: Terraform Plan e Apply & Ansible Provisioning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Comando
        run: echo "Teste Paulo Xavier"
      
