image: python
stages:
- build
- test
- deploy
build-job:
  stage: build
  script:
    - python3 -V
test-job:
  stage: test
  script:
    - echo "teste paulo xavier"
deploy-job:
  stage: deploy
  script:
    - echo "Finalizado!"
